### ISSUE TITLE
Drop 'PREVIEW' from V4 emulator

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#1033]
## Version
Latest

## Describe the bug
We should drop 'PREVIEW' from the product name. 
The new name should consistently be 'Bot Framework Emulator'.

[bug]

**Comment by tonyanziano** [comment]
Addressed in #1039

**Comment by justinwilaby** [comment]
reopening this ticket as we still see some areas displaying PREVIEW
