### ISSUE TITLE
Adaptive Card form breaks emulator interface.

### ISSUE THREAD

**Issue by paulmains** [Microsoft/BotFramework-Emulator#1091]
## Version
4.1.0

## Describe the bug
When getting to a dialog that uses an adaptive card with form fields the entire interface vanishes. There's no error (i can't seem to find any logging). This happens on both development and production endpoints.

The form renders fine on a very basic test demo client. However that is pointing at the production app and not my local. I've been using the bot emulator for debugging the local bot.

## To Reproduce
1. I've built an adaptive card (v 1.0.3 and v 1.0.0) with text blocks, text inputs, a choice set input and a toggle input. With a submit action also.
2. Go to that part of the dialog that triggers the form.
3. Interface vanishes.

## Expected behavior
The interface should remain and the form should be rendered.

### Before the response was submitted that triggers the issue
![before response submission that triggers the issue](https://user-images.githubusercontent.com/20128762/48571843-cd17e580-e8ff-11e8-8ae6-65bf9fef77fc.jpg)

### Once the response has been submitted the interface dissapears, leaving a blank window.
![after the response submission that triggers the issue](https://user-images.githubusercontent.com/20128762/48571848-d012d600-e8ff-11e8-8964-9b6ada072b65.jpg)

### On a demo page that is pointing at the production endpoint the form renders correctly
![demo client (not using bot emulator)](https://user-images.githubusercontent.com/20128762/48571854-d2753000-e8ff-11e8-8101-5e02d8daf5f4.jpg)

## Additional context
The methods that i used to create the card response is the following.

```C#
public static IMessageActivity SendClientForm(ITurnContext turnContext, dynamic data)
        {
            var response = turnContext.Activity.CreateReply();
            var card = BuildClientForm(data.Message).ToJson();
            
            response.Attachments = new List<Attachment>
            {
                new Attachment
                {
                    ContentType = "application/vnd.microsoft.card.adaptive",
                    Content = card,
                }
            };

            return response;
        }

        private static AdaptiveCard BuildClientForm(dynamic data)
        {
            var card = new AdaptiveCard();

            card.Body.Add(new AdaptiveTextBlock
            {
                Spacing = AdaptiveSpacing.Medium,
                Text = FindCandidateStrings.FORM_TITLE_LABEL,
                Weight = AdaptiveTextWeight.Lighter,
                Size = AdaptiveTextSize.ExtraLarge,
                Wrap = true
            });

            card.Body.Add(new AdaptiveTextBlock
            {
                Text = FindCandidateStrings.FORM_NAME_LABEL,
            });

            card.Body.Add(new AdaptiveTextInput
            {
                Id = "name",
                MaxLength = 100,
            });

            card.Body.Add(new AdaptiveTextBlock
            {
                Text = FindCandidateStrings.FORM_EMAIL_LABEL,
            });

            card.Body.Add(new AdaptiveTextInput
            {
                Id = "email",
                MaxLength = 100,
            });

            card.Body.Add(new AdaptiveTextBlock
            {
                Text = FindCandidateStrings.FORM_PHONE_LABEL,
            });

            card.Body.Add(new AdaptiveTextInput
            {
                Id = "phone",
                MaxLength = 20,
            });

            card.Body.Add(new AdaptiveTextBlock
            {
                Text = FindCandidateStrings.FORM_MESSAGE_LABEL,
            });

            card.Body.Add(new AdaptiveTextInput
            {
                Id = "message",
                MaxLength = 500,
                IsMultiline = true,
                Value = data
            });

            card.Body.Add(new AdaptiveTextBlock
            {
                Text = FindCandidateStrings.FORM_MARKET_LABEL,
            });

            card.Body.Add(new AdaptiveChoiceSetInput
            {
                Id = "market",
                Style = AdaptiveChoiceInputStyle.Compact,
                IsMultiSelect = false,
                Value = "",
                Choices = GetMarketChoices()
            });

            card.Body.Add(new AdaptiveTextBlock
            {
                Text = FindCandidateStrings.FORM_NUMBER_LABEL,
            });

            card.Body.Add(new AdaptiveNumberInput()
            {
                Id = "phone",
                Placeholder = FindCandidateStrings.FORM_NUMBER_PLACEHOLDER,
                Min = 1
            });

            card.Body.Add(new AdaptiveTextBlock
            {
                Text = FindCandidateStrings.FORM_INDUSTRY_LABEL,
            });

            card.Body.Add(new AdaptiveTextInput
            {
                Id = "industry",
                MaxLength = 100
            });

            card.Body.Add(new AdaptiveToggleInput()
            {
                Id = "acceptTerms",
                Title = FindCandidateStrings.FORM_PRIVACY_POLICY,
                Value = "false",
                ValueOn = "true",
                ValueOff = "false"
            });

            card.Body.Add(new AdaptiveTextBlock
            {
                Text = FindCandidateStrings.FORM_REQUIRED_LABEL,
                Size = AdaptiveTextSize.Small,
                Weight = AdaptiveTextWeight.Lighter
            });

            card.Actions.Add(new AdaptiveSubmitAction()
            {
                Title = "Submit"
            });
            return card;
        }

        private static List<AdaptiveChoice> GetMarketChoices()
        {
            var choices = FindCandidateStrings.FORM_MARKET_CHOICES.Split('|').ToList();
            var adaptiveChoices = new List<AdaptiveChoice>
            {
                new AdaptiveChoice
                {
                    Title = FindCandidateStrings.FORM_DEFAULT_SELECT,
                    Value = "0",
                }
            };

            foreach (var choice in choices)
            {
                adaptiveChoices.Add(new AdaptiveChoice{ Title = choice, Value = choice});
            }

            return adaptiveChoices;
        }
```

[bug]

**Comment by justinwilaby** [comment]
This looks like a webchat issue. I'll investigate.

**Comment by justinwilaby** [comment]
@paulmains - Do you have the adaptive card json handy?

**Comment by paulmains** [comment]
Hi @justinwilaby i wasn't using json, but using the data in this ticket I quickly created one. That version works fine, however when you create one in C# using the AdaptiveCard library it breaks in the emulator (but works fine in the web client)

{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
        "type": "TextBlock",
        "spacing":"medium",
        "size": "extraLarge",
        "weight":"lighter",
        "text": "Form title",
        "wrap": true,
        "maxLines": 0
    },
    {
        "type": "TextBlock",
        "text": "form name label"
    },
    {
        "id": "name",
        "type": "Input.Text",
        "maxLength": 100
    },
    {
        "type": "TextBlock",
        "text": "form email label"
    },
    {
        "id": "email",
        "type": "Input.Text",
        "maxLength": 100
    },
    {
        "type": "TextBlock",
        "text": "form phone label"
    },
    {
        "id": "phone",
        "type": "Input.Text",
        "maxLength": 20
    },
    {
        "type": "TextBlock",
        "text": "form message label"
    },
    {
        "id": "message",
        "type": "Input.Text",
        "maxLength": 500,
        "isMultiLine": true,
        "value": "message"
    },
    {
        "type": "TextBlock",
        "text": "form market label"
    },
    {
        "id": "market",
        "type": "Input.ChoiceSet",
        "maxLength": 20,
        "style": "compact",
        "value": "",
        "choices": [{
            "title": "please select",
            "value": "0"
        }]
    },
    {
        "type": "TextBlock",
        "text": "form number label"
    },
    {
        "id": "number",
        "type": "Input.Number",
        "maxLength": 20
    },
    {
        "type": "TextBlock",
        "text": "form industry label"
    },
    {
        "id": "industry",
        "type": "Input.Text",
        "maxLength": 100
    },
    {
        "type": "Input.Toggle",
        "id": "acceptTerms",
        "title": "privacy policy",
        "value": "false",
        "valueOn": "true",
        "valueOff": "false"
    },
    {
        "type": "TextBlock",
        "text": "form required label",
        "size": "small",
        "weight": "lighter"
    }
  ],
  "actions":[
      {
          "type":"Action.Submit",
          "title": "Submit"
      }
  ]
}

**Comment by compulim** [comment]
@paulmains do you mean it work in Web Chat but not in Emulator? Are you using Web Chat v4?

@corinagum can you repro it in Web Chat v3/v4. We often need to debug Adaptive Cards, it will be a great if MockBot can take an uploaded file (JSON of Adaptive Cards), and reply as an Adaptive Card activity.

**Comment by compulim** [comment]
@paulmains ❤ your inspection into the web page. I almost forgot we added `<meta>` tag to help user finding out the version and variant of Web Chat they are using.

Emulator is using Web Chat v3 for now, we will bump it to v4 in Feb release. So it is a good guess that a bug in Web Chat v3 is plaguing Emulator.

@corinagum we can scope down to v3.

**Comment by justinwilaby** [comment]
@paulmains - can you please confirm this has been fixed with the bump to WebChat 4.0 in our nightly release?

**Comment by cwhitten** [comment]
We've upgraded the WebChat in the Emulator and this should no longer be an issue. Please reopen if you've updated your Emulator version (>=4.2.1) and are still seeing this issue.
