### ISSUE TITLE
Trace Activities don't render in inspector and error out in webchat chat pane

### ISSUE THREAD

**Issue by stevengum** [Microsoft/BotFramework-Emulator#1328]
## Version
Nightly: **4.2.149424**

## Describe the bug
**Bot connected via endpoint**
Trace activities don't show up in the activity inspector, and render (improperly) in the chat pane:

![trace-activity-rendering-problem](https://user-images.githubusercontent.com/14935595/53361252-2ffc1e00-38ec-11e9-8562-2a93cbb1db36.jpg)

[bug]

**Comment by tonyanziano** [comment]
Fixed with #1334 & #1335. Expect the fix to be in tonight's nightly build.

**Comment by v-kydela** [comment]
Despite those pull requests that predate 4.3.0, this issue persists in 4.3.0:

![image](https://user-images.githubusercontent.com/41968495/53988499-7580ce00-40d8-11e9-8395-99a693e6adc0.png)

Just like @darrenj described in https://github.com/Microsoft/BotFramework-Emulator/issues/1347, I'm observing Emulator trying to render traces that are triggered by a LUIS recognizer

Should this issue be reopened or should a new issue be created?

**Comment by a-b-r-o-w-n** [comment]
Closing this as a duplicate of #1358
