### ISSUE TITLE
With BOT Emulator 4.3.0 no "name" is provided

### ISSUE THREAD

**Issue by LongBeachHXC** [Microsoft/BotFramework-Emulator#1350]
With the new release of the BOT Emulator when messages are submitted there is no longer a "name" reference. With the previous release it would get submitted with the generic username "User." Please include this back in.

**Comment by justinwilaby** [comment]
I believe you are referring to the `name` field in the `from` property. Is that correct?

```json
{
  "channelData": {
    "clientActivityID": "15519088410680.fj70rnerp8u",
    "state": "sent"
  },
  "channelId": "emulator",
  "conversation": {
    "id": "5a013590-4054-11e9-a0d3-9b66847d3db7|livechat"
  },
  "from": {
    "id": "r_696wgb7q8x",
    "role": "user"
              <----------------- NAME SHOULD BE HERE BUT ISN'T ------------------
  },
  "id": "6b79eb50-4059-11e9-b873-1d7bbe8d0014",
  "localTimestamp": "2019-03-06T13:47:21-08:00",
  "locale": "en",
  "recipient": {
    "id": "118",
    "name": "Bot",
    "role": "bot"
  },
  "serviceUrl": "https://5a33bb50.ngrok.io",
  "showInInspector": true,
  "text": "Hello!",
  "textFormat": "plain",
  "timestamp": "2019-03-06T21:47:21.093Z",
  "type": "message"
}
```

**Comment by LongBeachHXC** [comment]
Yes...you are correct

**Comment by a-b-r-o-w-n** [comment]
@LongBeachHXC This was fixed yesterday and was released in our [nightly build](https://github.com/Microsoft/botframework-emulator-nightlies/releases) (ignore the 4.2.xxx tag, we are working to get that corrected).

**Comment by LongBeachHXC** [comment]
@justinwilaby @a-b-r-o-w-n I really appreciate the fast response on this.

**Comment by LongBeachHXC** [comment]
@justinwilaby @a-b-r-o-w-n it appears that the emulator is still not passing a "name" property within the TurnContext Activity...I downloaded the bot emulator nightly build referenced above. Below is console log output of the TurnContext Activity and also provided a snapshot of my bot emulator version.

![image](https://user-images.githubusercontent.com/31868262/53985675-1ec3c600-40d1-11e9-8286-b5677cd99501.png)

TurnContext: {
  "text": "show my pipeline",
  "textFormat": "plain",
  "type": "message",
  "channelData": {
    "clientActivityID": "15519888950510.vs9kup5yivn"
  },
  "channelId": "emulator",
  "from": {
    "id": "r_6pb6959mll",
    "role": "user"
  },
  "locale": "10.13.13.238",
  "timestamp": "2019-03-07T20:01:35.062Z",
  "conversation": {
    "id": "5ffa0b70-4112-11e9-9661-699032a7717d|livechat"
  },
  "id": "cf5c2f60-4113-11e9-a86d-79fe1c6ed4f7",
  "localTimestamp": "2019-03-07T20:01:35.000Z",
  "recipient": {
    "id": "2",
    "name": "Bot",
    "role": "bot"
  },
  "serviceUrl": "https://fa463a72.ngrok.io"
}

**Comment by a-b-r-o-w-n** [comment]
@LongBeachHXC There was an issue with our nightly builds that was just fixed. Can you try again on the latest? https://github.com/Microsoft/botframework-emulator-nightlies/releases/tag/4.3.050674

**Comment by LongBeachHXC** [comment]
@a-b-r-o-w-n we are good to go. Again, I appreciate you all getting on this!
