### ISSUE TITLE
Can't sign in to Azure With TFA Accounts

### ISSUE THREAD

**Issue by yochay** [Microsoft/BotFramework-Emulator#861]
Latest build  -Preview.39289

Trying to log-in and keep getting this error 
![image](https://user-images.githubusercontent.com/896149/45520732-9a226b80-b76f-11e8-987b-2de70079b1cd.png)

**Comment by justinwilaby** [comment]
Accounts that require two factor auth are not currently supported.

**Comment by justinwilaby** [comment]
@yochay  - Does your azure login require two factor auth?

**Comment by mikepugh** [comment]
I'm running into this problem as well - yes my account requires two factor auth.

**Comment by dsghi** [comment]
This should be a higher priority to fix. MFA is considered a best practice for Azure admin accounts, and it's pushed hard by the Advisor and Security Center features if it's not in use.

**Comment by mikepugh** [comment]
Looks like there's already an active PR for this #924

**Comment by habuso** [comment]
I am running into the same issue and my account doesn't have tfa.

**Comment by justinwilaby** [comment]
Fixed with #924

**Comment by GillesBodart** [comment]
Hello, I'm using Okta as a tfa but the fix doesn't seem to work for me
![image](https://user-images.githubusercontent.com/10420055/46127940-685ed980-c232-11e8-84f0-3ac933a7fb08.png)
![image](https://user-images.githubusercontent.com/10420055/46127965-77458c00-c232-11e8-835a-647b8d90aa0b.png)

**Comment by habuso** [comment]
I also tried to fix it, but still experiencing the same issue as well.
