### ISSUE TITLE
Emulator: on Mac, opening a .bot file with the Emulator from OS launches Emulator but does not open .bot file

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#947]
## Version
 Mac: Emulator_OSX_v4.0.0-preview.40025_40380

## Describe the bug
From file browser, opening a .bot file by double-clicking or contextual menu launches the Emulator but does not open the .bot file. The Emulator shows the Welcome tab.

## To Reproduce
1. In Finder, go to your bot folder.
2. Right-click .bot file, and select Emulator (or double-click).
3. Emulator launches, but no .bot file is open.

## Screenshots
![image](https://user-images.githubusercontent.com/39317542/46315120-60c86900-c581-11e8-9ebf-d7370297f807.png)
![image](https://user-images.githubusercontent.com/39317542/46315142-7178df00-c581-11e8-8967-d187392ee834.png)

[bug]

**Comment by justinwilaby** [comment]
I was able to repro this and did see a problem. I'm working on a fix for this now.

**Comment by justinwilaby** [comment]
Fixed by #970

**Comment by mewa1024** [comment]
@justinwilaby I'm still having this problem on the Mac build from October 12: 4.0.0-preview-one-off.
Double-clicking .bot file launches Emulator, but no .bot file is open:

<img width="1680" alt="screen shot 2018-10-12 at 7 52 23 pm 2" src="https://user-images.githubusercontent.com/39317542/46900528-6e6ed000-ce58-11e8-9864-23d6f80fde62.png">
<img width="1680" alt="screen shot 2018-10-12 at 7 52 41 pm 2" src="https://user-images.githubusercontent.com/39317542/46900531-729aed80-ce58-11e8-833a-a0a9772631ca.png">

**Comment by justinwilaby** [comment]
I have confirmed this is fixed on `4.0.50000`
